version: '3'

services:
  beat:
    image: mcasimir/journalbeat

    environment:
      ELASTICSEARCH_HOST: elasticsearch.example.com:9200
      LOG_LEVEL: debug

    volumes:
      - "/var/tmp/journalbeat:/data"
      - "/var/log/journal:/var/log/journal"

    deploy:
      mode: "global"
