version: '3'

services:
  beat:
    image: mcasimir/journalbeat

    env_file: .env

    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"

    volumes:
      - "/run/log/journal:/var/log/journal:ro"
      - "/etc/machine-id:/etc/machine-id:ro"

    deploy:
      mode: "global"
