version: '3'

services:
  beat:
    image: mcasimir/journalbeat

    environment:
      ELASTICSEARCH_HOST: elasticsearch.example.com:9200
      LOG_LEVEL: warning

    volumes:
      - "$PWD/data:/data"
      - "/run/log/journal:/var/log/journal"
      - "/etc/machine-id:/etc/machine-id"

    deploy:
      mode: "global"
