journalbeat:
  clean_field_names: true
  seek_position: cursor
  cursor_seek_fallback: tail
  write_cursor_state: true
  cursor_state_file: /data/journalbeat-cursor-state
  cursor_flush_period: 5s

name: journalbeat
tags: ["CONTAINER_ID", "CONTAINER_ID_FULL", "CONTAINER_NAME", "CONTAINER_TAG", "CONTAINER_PARTIAL_MESSAGE"]

fields:
  env: ${ENVIRONMENT_NAME:journalbeat}

processors:
- drop_event:
    when:
      regexp:
        container_name: "^journalbeat"

output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_HOST}"]

logging.level: ${LOG_LEVEL:info}
logging.to_files: false
